server:
  servlet:
    context-path: /diemme

spring:
  data:
      mongodb:
        user:
        password: 
        uri: mongodb://127.0.0.1:27017/diemme
  application:
    name: diemme
  datasource:
    url: jdbc:mysql://127.0.0.1:8889/diemme?serverTimezone=Europe/Rome
    username: diemme
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver    
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  messages:
    basename: i18n/common, i18n/diemme
    encoding: UTF-8
    use-code-as-default-message: true
  logging:
    file:
      name: ./file.log
    level:
      root: INFO
email:
  host: xxx
  port: 2525
  username: xxx
  password: xxxx
  systemMail: xx@mailtrap.io
  tls: true

        

    
