server:
  servlet:
    context-path: /diemme

spring:
  data:
      mongodb:
        user: diemme
        password: diemme
        uri: mongodb://127.0.0.1:27017/diemme
  application:
    name: diemme
  datasource:
    url: jdbc:mysql://localhost:8889/diemme?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: diemme
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver    
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  messages:
    basename: i18n/common, i18n/diemme
    encoding: UTF-8
    use-code-as-default-message: true
    
        

    
